---
version: '3'

include:
  - ./configs/downstream1/docker-compose.yaml
  - ./configs/downstream2/docker-compose.yaml
  - ./configs/upstream1/docker-compose.yaml

services:
  reqgenerator:
    container_name: reqgenerator
    image: golang:1.20
    cap_add:
      - NET_ADMIN
    depends_on:
      - downstream1_node
      - downstream2_node
    volumes:
      - ./:/go/src/xbl
    working_dir: /go/src/xbl
    restart: unless-stopped
    networks:
      - external
    command: ["go", "run", "main.go", "reqgenerator"]


networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.145.145.0/24
  external:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.200.200.0/24