---
global:
  scrape_interval: 5s
  scrape_timeout: 1s

scrape_configs:
  - job_name: debug
    metrics_path: /metrics
    static_configs:
      - targets:
          - '10.200.200.20:8080'
          - '10.145.145.11:8080'
          - '10.145.145.13:8080'